// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TCSASystems.Blazor.EmployeeManagement.Data;

#nullable disable

namespace TCSASystems.Blazor.EmployeeManagement.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TCSASystems.Blazor.EmployeeManagement.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/225.jpg",
                            Name = "Nora Kulas",
                            Position = 8,
                            Salary = 59195m,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/857.jpg",
                            Name = "Freida Cartwright",
                            Position = 8,
                            Salary = 67616m,
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/751.jpg",
                            Name = "Faustino Herman",
                            Position = 0,
                            Salary = 81583m,
                            Type = 3
                        },
                        new
                        {
                            Id = 4,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1047.jpg",
                            Name = "Godfrey Parker",
                            Position = 6,
                            Salary = 54628m,
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1.jpg",
                            Name = "Lessie Fahey",
                            Position = 1,
                            Salary = 44614m,
                            Type = 2
                        },
                        new
                        {
                            Id = 6,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/987.jpg",
                            Name = "Adela Nolan",
                            Position = 1,
                            Salary = 57831m,
                            Type = 3
                        },
                        new
                        {
                            Id = 7,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/16.jpg",
                            Name = "Hester Hodkiewicz",
                            Position = 0,
                            Salary = 60909m,
                            Type = 2
                        },
                        new
                        {
                            Id = 8,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/937.jpg",
                            Name = "Bernardo Conroy",
                            Position = 7,
                            Salary = 65305m,
                            Type = 2
                        },
                        new
                        {
                            Id = 9,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/630.jpg",
                            Name = "Ashleigh Bogisich",
                            Position = 2,
                            Salary = 96102m,
                            Type = 3
                        },
                        new
                        {
                            Id = 10,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/280.jpg",
                            Name = "Meda Jerde",
                            Position = 3,
                            Salary = 86047m,
                            Type = 0
                        },
                        new
                        {
                            Id = 11,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/95.jpg",
                            Name = "Clementine Bode",
                            Position = 6,
                            Salary = 77600m,
                            Type = 3
                        },
                        new
                        {
                            Id = 12,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/139.jpg",
                            Name = "Marge Bernhard",
                            Position = 9,
                            Salary = 34132m,
                            Type = 3
                        },
                        new
                        {
                            Id = 13,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/891.jpg",
                            Name = "Olga Schultz",
                            Position = 8,
                            Salary = 42368m,
                            Type = 2
                        },
                        new
                        {
                            Id = 14,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/704.jpg",
                            Name = "Marie Schuppe",
                            Position = 3,
                            Salary = 56603m,
                            Type = 3
                        },
                        new
                        {
                            Id = 15,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/936.jpg",
                            Name = "Josianne Fisher",
                            Position = 6,
                            Salary = 91276m,
                            Type = 3
                        },
                        new
                        {
                            Id = 16,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/613.jpg",
                            Name = "Osborne Botsford",
                            Position = 7,
                            Salary = 85966m,
                            Type = 1
                        },
                        new
                        {
                            Id = 17,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1166.jpg",
                            Name = "Delilah Dickinson",
                            Position = 1,
                            Salary = 80345m,
                            Type = 0
                        },
                        new
                        {
                            Id = 18,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1005.jpg",
                            Name = "Jermey Mosciski",
                            Position = 2,
                            Salary = 83753m,
                            Type = 0
                        },
                        new
                        {
                            Id = 19,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/2.jpg",
                            Name = "Madonna Zboncak",
                            Position = 5,
                            Salary = 58519m,
                            Type = 0
                        },
                        new
                        {
                            Id = 20,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/27.jpg",
                            Name = "Jaren Dicki",
                            Position = 0,
                            Salary = 54498m,
                            Type = 0
                        },
                        new
                        {
                            Id = 21,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1043.jpg",
                            Name = "Marc Fadel",
                            Position = 8,
                            Salary = 90102m,
                            Type = 0
                        },
                        new
                        {
                            Id = 22,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/455.jpg",
                            Name = "Alycia McClure",
                            Position = 7,
                            Salary = 88080m,
                            Type = 2
                        },
                        new
                        {
                            Id = 23,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1056.jpg",
                            Name = "Giuseppe Koepp",
                            Position = 6,
                            Salary = 45733m,
                            Type = 1
                        },
                        new
                        {
                            Id = 24,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1133.jpg",
                            Name = "Bernard Brown",
                            Position = 5,
                            Salary = 32217m,
                            Type = 2
                        },
                        new
                        {
                            Id = 25,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/442.jpg",
                            Name = "Gina Kuvalis",
                            Position = 2,
                            Salary = 48631m,
                            Type = 2
                        },
                        new
                        {
                            Id = 26,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/118.jpg",
                            Name = "Shany Konopelski",
                            Position = 7,
                            Salary = 37239m,
                            Type = 3
                        },
                        new
                        {
                            Id = 27,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/114.jpg",
                            Name = "Jarvis O'Reilly",
                            Position = 8,
                            Salary = 89908m,
                            Type = 3
                        },
                        new
                        {
                            Id = 28,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/151.jpg",
                            Name = "Sven Schowalter",
                            Position = 4,
                            Salary = 87837m,
                            Type = 3
                        },
                        new
                        {
                            Id = 29,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/207.jpg",
                            Name = "Marcia Cremin",
                            Position = 7,
                            Salary = 90414m,
                            Type = 1
                        },
                        new
                        {
                            Id = 30,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1189.jpg",
                            Name = "Estelle Greenholt",
                            Position = 0,
                            Salary = 52666m,
                            Type = 2
                        },
                        new
                        {
                            Id = 31,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/811.jpg",
                            Name = "Helena Stracke",
                            Position = 1,
                            Salary = 62390m,
                            Type = 2
                        },
                        new
                        {
                            Id = 32,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/933.jpg",
                            Name = "Samanta Mayert",
                            Position = 7,
                            Salary = 78554m,
                            Type = 1
                        },
                        new
                        {
                            Id = 33,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/438.jpg",
                            Name = "Mitchell Feil",
                            Position = 3,
                            Salary = 67377m,
                            Type = 0
                        },
                        new
                        {
                            Id = 34,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/573.jpg",
                            Name = "Sarai Batz",
                            Position = 9,
                            Salary = 76405m,
                            Type = 0
                        },
                        new
                        {
                            Id = 35,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1010.jpg",
                            Name = "Heaven Jerde",
                            Position = 5,
                            Salary = 66707m,
                            Type = 1
                        },
                        new
                        {
                            Id = 36,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/790.jpg",
                            Name = "Henderson Bergnaum",
                            Position = 5,
                            Salary = 66596m,
                            Type = 3
                        },
                        new
                        {
                            Id = 37,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/726.jpg",
                            Name = "Earnestine Dickinson",
                            Position = 4,
                            Salary = 94882m,
                            Type = 3
                        },
                        new
                        {
                            Id = 38,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/190.jpg",
                            Name = "Deven Dach",
                            Position = 3,
                            Salary = 40342m,
                            Type = 1
                        },
                        new
                        {
                            Id = 39,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1095.jpg",
                            Name = "Scot Hettinger",
                            Position = 4,
                            Salary = 46603m,
                            Type = 2
                        },
                        new
                        {
                            Id = 40,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/668.jpg",
                            Name = "Tatum Johns",
                            Position = 4,
                            Salary = 93370m,
                            Type = 2
                        },
                        new
                        {
                            Id = 41,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1170.jpg",
                            Name = "Kay Cartwright",
                            Position = 4,
                            Salary = 35709m,
                            Type = 1
                        },
                        new
                        {
                            Id = 42,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/691.jpg",
                            Name = "Marshall Keebler",
                            Position = 6,
                            Salary = 95460m,
                            Type = 2
                        },
                        new
                        {
                            Id = 43,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/819.jpg",
                            Name = "Amir Hegmann",
                            Position = 5,
                            Salary = 74360m,
                            Type = 0
                        },
                        new
                        {
                            Id = 44,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/112.jpg",
                            Name = "Dovie Gutmann",
                            Position = 7,
                            Salary = 56716m,
                            Type = 0
                        },
                        new
                        {
                            Id = 45,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1054.jpg",
                            Name = "Richie Kunde",
                            Position = 0,
                            Salary = 47242m,
                            Type = 3
                        },
                        new
                        {
                            Id = 46,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/860.jpg",
                            Name = "Jailyn Koelpin",
                            Position = 1,
                            Salary = 83978m,
                            Type = 3
                        },
                        new
                        {
                            Id = 47,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1084.jpg",
                            Name = "Shannon Bogisich",
                            Position = 2,
                            Salary = 62063m,
                            Type = 2
                        },
                        new
                        {
                            Id = 48,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/845.jpg",
                            Name = "Mavis Steuber",
                            Position = 7,
                            Salary = 58624m,
                            Type = 0
                        },
                        new
                        {
                            Id = 49,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/557.jpg",
                            Name = "Lorine Block",
                            Position = 3,
                            Salary = 94796m,
                            Type = 3
                        },
                        new
                        {
                            Id = 50,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/192.jpg",
                            Name = "Jolie King",
                            Position = 2,
                            Salary = 60565m,
                            Type = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
